packages/next-app/package.json, packages/next-app/src/components/MainBox.tsx, packages/next-app/src/components/Wallet.tsx, packages/next-app/src/hooks/useWindowDimensions.ts, packages/next-app/src/pages/_app.tsx, packages/next-app/src/pages/index.tsx, yarn.lock
Added wallet components to allow users to connect via either Metamask or Wallet Connect
wagmi-xyz was used 
Closes #...
=> [Added] Wallet connect and Metamask

packages/next-app/src/components/MainBox.tsx
Fixes confetti width, heigth and colors
no
no
Rebased and prettified version of the original https://github.com/Developer-DAO/code-claim-site/pull/24
=> Fix confetti effect

packages/next-app/public/assets/eligible-check.svg, packages/next-app/src/components/ClaimCard.tsx, packages/next-app/src/pages/index.tsx
Updated claim card according to latest design at https://www.figma.com/file/TiqfRJnNxOQOSjA2TMkagD/%24CODE-Airdrop-Site-Designs?node-id=358%3A2107
No
No
No
=> Updated claim card

packages/next-app/src/components/Logo.tsx
Updates logo component in header to be responsive (meaning showing only the logo for mobile - no text).
Closes #16
=> Make header responsive

packages/next-app/src/components/Wallet.tsx
Fixes text alignment
No
No
Before:
After:
No
=> Mobile "Wallet connected" button alignment

packages/hardhat/src/CODE.sol, packages/hardhat/src/ClaimCODE.sol
First, we keep the CODE a simple ERC20 and with RBAC and creating a new  contract that deals with the claiming. This offers more flexibility in terms of future developments
A discussion was raised on the #tokenomics related with how future CODE will be minted to treasury
Closes #...
=> Proposing a new way of claiming CODE.

packages/hardhat/src/ClaimCODE.sol
=> When claiming we moved from mint to transfer to save gas

packages/next-app/public/assets/arrow-down.svg, packages/next-app/public/assets/arrow-up.svg, packages/next-app/src/pages/index.tsx
Adds scroll snap and scroll arrows
No
No
Closes #15
=> Scroll snap

packages/next-app/src/components/ClaimCard.tsx, packages/next-app/src/components/MainBox.tsx, packages/next-app/src/pages/index.tsx
Moves confetti from MainBox.tsx to index.tsx.
Adds confetti state.
Adds confetti state callback to ClaimCard.tsx
=> Confetti callback

packages/next-app/.prettierrc, packages/next-app/__tests__/pages/snapshot.tsx, packages/next-app/ethereum.d.ts, packages/next-app/src/components/ClaimCard.tsx, packages/next-app/src/components/Wallet.tsx, packages/next-app/src/hooks/useConfirmations.ts, packages/next-app/src/hooks/useContractInfo.ts, packages/next-app/src/typechain/CODEToken.d.ts, packages/next-app/src/typechain/ERC20.d.ts, packages/next-app/src/typechain/ERC20Permit.d.ts, packages/next-app/src/typechain/IERC20.d.ts, packages/next-app/src/typechain/IERC20Metadata.d.ts, packages/next-app/src/typechain/IERC20Permit.d.ts, packages/next-app/src/typechain/Ownable.d.ts, packages/next-app/src/typechain/common.d.ts, packages/next-app/src/typechain/factories/CODEToken__factory.ts, packages/next-app/src/typechain/factories/ERC20Permit__factory.ts, packages/next-app/src/typechain/factories/ERC20__factory.ts, packages/next-app/src/typechain/factories/IERC20Metadata__factory.ts, packages/next-app/src/typechain/factories/IERC20Permit__factory.ts, packages/next-app/src/typechain/factories/Ownable__factory.ts, packages/next-app/test.js
Add prettier which was merged into the wrong branch in https://github.com/Developer-DAO/code-claim-site/pull/40 - created by @helloitsm3
=> Add prettier

packages/next-app/src/components/ClaimCard.tsx, packages/next-app/src/components/ClaimCardComponents.tsx
Refactors `ClaimCard` extracting components to a separate file thus separating views and logic a lil more.
Everything should still work as expected.
Closes #45
=> Refactor claim card

packages/next-app/public/assets/block-confirmations.svg
Animates block confirmations blob
Closes #52
=> Animate block confirmations blob

packages/hardhat/src/mocks/MerkleProofWrapper.sol, packages/hardhat/test/MerkleProof.test.ts
Tests for the MerkleProof.sol library.
None
None
Closes #2
=> Tests for MerkleProof.sol #2

packages/next-app/src/components/Button.tsx, packages/next-app/src/components/MainBox.tsx, packages/next-app/src/components/Wallet.tsx, packages/next-app/src/pages/index.tsx
* Fixes switching network
* Fixes learn more button width on mobile
Based on preview branch. ⚠️
=> Fix switch network

packages/next-app/__tests__/pages/__snapshots__/snapshot.tsx.snap, packages/next-app/src/components/SocialLinks.tsx, packages/next-app/src/components/SocialLinksMobile.tsx, packages/next-app/src/pages/index.tsx
* Adds underline animation for social links (on web)
* Introduces separate component for social links on mobile (as it makes maintenance easier)
Closes #59
=> Add underline animation

packages/hardhat/deploy/00_deploy_token.ts, packages/hardhat/src/CODEToken.sol, packages/hardhat/test/CODEToken.test.ts
* Check claimable period, `$CODE` is not claimable after claim period ends
* Coverage more test cases, now the test coverage for `CODEToken.sol` is 100%
```
-------------------------|----------|----------|----------|----------|----------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
src/                    |    53.33 |    46.67 |    44.44 |    53.33 |                |
CODE.sol               |        0 |      100 |        0 |        0 |       13,17,21 |
CODEToken.sol          |      100 |      100 |      100 |      100 |                |
ClaimCODE.sol          |        0 |        0 |        0 |        0 |... 83,84,88,89 |
MerkleProof.sol        |      100 …
```
=> Add claimable period check and coverage more test cases

packages/next-app/src/components/ClaimCard.tsx, packages/next-app/src/hooks/useContractInfo.ts
=> (fix): Use ClaimCODE contract in frontend

packages/hardhat/scripts/airdropSumCheck.ts
A wrap up for #12 , since the original PR has lost connection for months.
Closes #4
=> Add airdrop sum check script

packages/next-app/src/utils.ts, packages/next-app/src/utils/add-token.ts
=> fix: add token contract address envvar

packages/next-app/public/assets/placeholder-avatar.svg, packages/next-app/src/components/ClaimCardComponents.tsx, packages/next-app/src/components/MainBox.tsx, packages/next-app/src/components/Wallet.tsx, packages/next-app/src/components/toasts/error.tsx, packages/next-app/src/pages/index.tsx
Updates some styles after a feedback session with jazza.
Please see the individual commits for details.
=> Update styling after feedback session
